spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9098/realms/micro-services"
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
        - id: order-lines-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order-lines/**
        - id: product-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
        - id: payment-service
          uri: lb:http://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**
        - id: rating-service
          uri: lb:http://RATING-SERVICE
          predicates:
            - Path=/api/v1/ratings/**
        - id: recommender-service
          uri: lb:http://RECOMMENDER-SERVICE
          predicates:
            - Path=/api/v1/recommenders/**
        - id: static-client
          uri: lb:http://STATIC-CLIENT
          predicates:
            - Path=/**


jwt:
  auth:
    converter:
      resource-id: gateway-service
      principal-attribute: username

logging:
  level:
    org:
      springframework:
        security: DEBUG

application:
  config:
    customer-url: http://localhost:8090/api/v1/customers

server:
  port: 8222

#app:
#  keycloak:
#    login:
#      url: http://localhost:9098/realms/micro-services/protocol/openid-connect/token
#    grant-type: password
#    client-id: gateway-service
#    client-secret: kfueNNOgyYe7k0ZFK8xuWKkNwuvFXW6J