application:
  config:
    rating-url: http://localhost:8222/api/v1/ratings

server:
  port: 7070

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recommender
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect